---
- name: Deploy
  remote_user: root
  hosts: esamwad
  tasks:
    - name: Update .env file
      copy:
        src: ./.env.prod
        dest: /root/.env.prod

    - name: Update docker-compose file
      copy:
        src: ./docker-compose.yml
        dest: /root/docker-compose.yml

    - name: Pull latest image
      command: docker-compose pull

    - name: Stop docker
      command: docker-compose down

    - name: Start docker
      command: docker-compose up -d

    - name: Status docker
      shell: docker ps
