version: "3"

services:
  web:
    image: &web samagragovernance/esamwad-backend:5.1.9
    command: gunicorn --workers=4 --threads=16 settings.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/staticfiles
    expose:
      - 8000
    ports:
      - 8006:8000
    env_file:
      - ./.env.prod
    environment:
      - IS_WEB=true

  nginx:
    image: samagragovernance/esamwad-nginx:0.1.0
    volumes:
      - static_volume:/home/app/staticfiles
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  worker:
    image: samagragovernance/esamwad-backend:5.1.9
    restart: on-failure
    env_file:
      - ./.env.prod
    command: celery worker --app=settings.celery.app --concurrency=8 --hostname=worker@%h --loglevel=INFO

  scheduler:
    image: samagragovernance/esamwad-backend:5.1.9
    restart: on-failure
    env_file:
      - ./.env.prod
    command: celery beat --app=settings.celery.app --loglevel=INFO

volumes:
  static_volume:
